package org.purr.enums;

public enum ImageBufferType {
    STARTIMAGE_BUFFER,
    GREYSCALE_BUFFER,
    MEANSHIFT_BUFFER,
    FOCUSMAP_BUFFER,
    REGION_BUFFER,
    BRIGHTNESSMAP_BUFFER,
    DFMAP_BUFFER,
    PARALLAX_LEFT_BUFFER,
    PARALLAX_RIGHT_BUFFER,
    SIDE_BY_SIDE_BUFFER,
    ANAGLYPH_BUFFER
}
